desc 'Tests adding a root cert to simulator'
desc 'param: certificate_path (optional String) - Path to root certificate'
lane :test do |params|
  simulator_add_root_cert(certificate_path: params[:certificate_path])
end
